# Generated by Django 4.2.4 on 2025-04-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='', max_length=50)),
                ('SKU', models.CharField(default='', max_length=50)),
                ('Case', models.CharField(default='', max_length=50)),
                ('Quantity', models.IntegerField(default='')),
            ],
        ),
    ]
